import cv2
import numpy as np
import glob
import json
import os

# ==========================================
# KONFIGURASI (CUKUP UBAH BAGIAN INI SAJA)
# ==========================================
# Ganti jadi "biru" atau "oranye" sesuai folder yang mau di-train
TARGET_NAME = "orange"  

# Pastikan folder strukturmu sesuai. Contoh: training_datasets/biru_crop/*.webp
INPUT_PATTERN = f"training_data/{TARGET_NAME}/*.webp" 
OUTPUT_FILE   = f"models/{TARGET_NAME}_model.json"

# ==========================================
# LOGIKA PROGRAM (JANGAN DIUBAH)
# ==========================================
print(f"Target Training: {TARGET_NAME.upper()}")
print(f"Membaca dataset dari: {INPUT_PATTERN}")

# 1. Ambil semua file gambar
images = glob.glob(INPUT_PATTERN)

if len(images) == 0:
    print(f"Error: Tidak ada foto di {INPUT_PATTERN}")
    print("   Pastikan nama folder benar dan isinya file .webp")
    exit()

# List penampung pixel
all_h = []
all_s = []
all_v = []

print(f"Memproses {len(images)} foto...")

for img_path in images:
    img = cv2.imread(img_path)
    if img is None: continue

    # Convert ke HSV
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)
    
    # Ratakan array dan masukkan ke penampung
    all_h.extend(h.flatten())
    all_s.extend(s.flatten())
    all_v.extend(v.flatten())

# 2. PROSES STATISTIK (METODE PERCENTILE)
# Kita pakai Percentile (bukan Mean) karena lebih akurat membuang "sampah"
print("Menghitung statistik (Percentile Method)...")

# Kita potong 5% data teraneh (outlier) di bawah dan atas
lower_h = int(np.percentile(all_h, 5))
upper_h = int(np.percentile(all_h, 95))

# Saturation & Value toleransinya lebih longgar (2% cut)
lower_s = int(np.percentile(all_s, 2))
upper_s = int(np.percentile(all_s, 98))

lower_v = int(np.percentile(all_v, 2))
upper_v = int(np.percentile(all_v, 98))

# 3. SAFETY PADDING (PENGAMAN)
# Melonggarkan sedikit range biar gak terlalu kaku
pad_h = 5 
pad_sv = 20

lower_h = max(0, lower_h - pad_h)
upper_h = min(179, upper_h + pad_h)

lower_s = max(0, lower_s - pad_sv)
upper_s = min(255, upper_s + pad_sv)

lower_v = max(0, lower_v - pad_sv)
upper_v = min(255, upper_v + pad_sv)

# 4. SIMPAN KE FILE
data_model = {
    "target": TARGET_NAME,
    "lower": [lower_h, lower_s, lower_v],
    "upper": [upper_h, upper_s, upper_v],
    "note": "Generated by train_maker.py (Percentile Mode)"
}

# Pastikan folder 'models' ada dulu
# os.makedirs("models", exist_ok=True)

with open(OUTPUT_FILE, "w") as f:
    json.dump(data_model, f, indent=4)

print("\n  TRAINING SELESAI!")
print(f"   Target: {TARGET_NAME}")
print(f"   Range H: {lower_h} - {upper_h}")
print(f"   Range S: {lower_s} - {upper_s}")
print(f"   Range V: {lower_v} - {upper_v}")
print(f"   Hasil disimpan ke file: '{OUTPUT_FILE}'")